server:
  port: 8850
spring:
  application:
    name: consumertwo
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1:8848
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3307/othertest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver